[package]
name = "encryptedVault"
version = "0.1.0"
edition = "2021"

[dependencies]
pbkdf2 = { version = "0.13.0-pre.1"}
sha2 = "0.11.0-pre.4"
serde_json = "1.0.128"
aes = "0.9.0-pre.2"
aes-gcm = "0.11.0-pre.2"
crypto-common = "0.2.0-rc.1"
generic-array = "1.1.0"
